#!/usr/bin/python
from subprocess import call

location_file = 'locations-yucatan.txt'

header = True
nodes = list()

for line in file(location_file):
    if header:
        header = False
        continue

    p = line.split()
    nodes.append([p[0],p[2],p[3]])

fo = file('tmp_yucatan.node','w')

fo.write(str(len(nodes)) + ' 2 0 0\n')
for n in nodes:
    fo.write(' '.join(map(str,n)) + '\n')

fo.close()
print "running triangle ... ",
call(['./triangle/triangle', '-S 0', '-e', '-N', '-E', '-V', '-C', 'tmp_yucatan.node'])
print "done."

# process Delaunay output
'''
752769  3  0
   1    41871  39241  40212
   2    39241  41871  38616
   3    41871  40118  40625
   4    40118  40212  39241
   5    39914  40118  41571
   6    40118  41871  40212
   7    39241  41571  40118
   8    40625  40118  39914
   9    38616  40250  39241
tjhladish@capybara:~/work/dengue$ tail tmp_yucatan.1.ele 
752761    284934  284790  287390
752762    334137  336950  340887
752763    292486  292184  292061
752764    342957  342011  332663
752765    287390  284790  281746
752766    6313  6282  6859
752767    56390  56303  55932
752768    25539  52457  276295
752769    285603  285130  285811
# Generated by ./triangle/triangle tmp_yucatan.node
'''

element_header = True
