#!/bin/bash
#PBS -r y
#PBS -N dengue
#PBS -o auto_output/vac-all_historical_serotypes-climate.out
#PBS -e auto_output/vac-all_historical_serotypes-climate.err
#PBS -m ae
#PBS -M tjhladish@gmail.com
#PBS -W group_list=epi
#PBS -l walltime=12:00:00
#PBS -l nodes=1:ppn=1
#PBS -l pmem=3G
#PBS -t 1-1500

cd $PBS_O_WORKDIR
module load gsl gcc/4.7.2
for i in `seq 1 4`;
do
    ./abc_sql abc_vaccine.json --simulate
done
