#! /bin/sh
#PBS -N vac80m
#PBS -r y
#PBS -l walltime=96:00:00
#PBS -l nodes=16:ppn=32
#PBS -l pmem=4000mb
#PBS -W group_list=epi
#PBS -M tjhladish@gmail.com
#PBS -m abe

cd $PBS_O_WORKDIR
module load intel/2013 openmpi gsl
mpiexec vaccinate_abc_mpi abc_vaccine-80mos.json 2> vac_catchup-highFOI-novarEIP.err > vac_catchup-highFOI-novarEIP.out
#mpiexec gdb -command=gdb.cmd abc_mpi 2> dengue-full_ts.err > dengue-full_ts.out
