#d = read.table('yucatan_edges_w_lengths.out',header=T)
a = read.table("../../raw_data/all_yucatan_pixels.out", sep='\t')
#w = read.table("../../schools_and_workplaces.out",header=T)
l = read.table('../../locations-yucatan_final.txt', header=T)
png('workplaces_and_schools.png',width=1200, height=1000, res=130)
par(mar=c(5,5,2,2))
plot(a$V1, a$V2, pch='.', ylim=c(19.6, 21.65), xlim=c(-90.4, -87.5), asp=1, xlab='Longitude', ylab='Latitude', col='black', cex=1.5, cex.lab=1.5)
#points(h$x, h$y, pch='.',col='yellow')
points(l$x[l$type!='house'], l$y[l$type!='house'], pch='.', col='lightblue')
dev.off()
