#! /bin/sh
#PBS -N base40
#PBS -r y
#PBS -l walltime=24:00:00
#PBS -l nodes=2:ppn=20
#PBS -l pmem=4000mb
#PBS -W group_list=epi
#PBS -M tjhladish@gmail.com
#PBS -m abe

cd $PBS_O_WORKDIR
module load intel/2013 openmpi gsl
mpiexec vaccinate_abc_mpi abc_baseline.json 2> baseline40-reducedFOI.err > baseline40-reducedFOI.out
#mpiexec gdb -command=gdb.cmd abc_mpi 2> dengue-full_ts.err > dengue-full_ts.out
