swap: determine_immunity_swap_probs.cpp 
	g++ -O2 determine_immunity_swap_probs.cpp -o generate_swap_file

swap_omp: determine_immunity_swap_probs.cpp 
	g++ -O2 -fopenmp determine_immunity_swap_probs.cpp -o generate_swap_file_omp

