d = read.table('imm_vs_age.out')

png('age_vs_immunity.png', height=800, width=1000, res=150)
par(mar=c(5,4.5,2,2))
plot(d$V1, d$V3/d$V2, type='l', ylim=c(0,1), xlab='Age (years)', ylab='Fraction immune', lwd=2)
points(d$V1, d$V4/d$V2, type='l', ylim=c(0,1), col='red', lwd=2)
points(d$V1, d$V5/d$V2, type='l', ylim=c(0,1), col='green', lwd=2)
points(d$V1, d$V6/d$V2, type='l', ylim=c(0,1), col='blue', lwd=2)
legend('top',fill=c('black','red','green','blue'),legend=c('DENV1     ','DENV2     ','DENV3     ','DENV4'), horiz=T, bty='n')
dev.off()
